apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-api
  namespace: tasky
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasky-api
  template:
    metadata:
      labels:
        app: tasky-api
    spec:
      containers:
        - name: tasky-api
          image: 122610499688.dkr.ecr.us-east-1.amazonaws.com/tasky:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://tasky:taskypass@3.227.12.152:27017/tasky?authSource=admin"

