apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: tasky
spec:
  selector:
    app: tasky-api
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer

