apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: tasky
spec:
  type: LoadBalancer
  selector:
    app: tasky-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
