apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasky-api
  namespace: tasky
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tasky-api
  template:
    metadata:
      labels:
        app: tasky-api
    spec:
      serviceAccountName: tasky-sa
      containers:
        - name: tasky-api
          image: 122610499688.dkr.ecr.us-east-1.amazonaws.com/tasky:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URI
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URI
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_URI
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: MONGO_DB
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: tasky-mongo
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: tasky-mongo
                  key: MONGO_PASS

